
name: 10-test
on:
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ github.token }}

permissions: write-all

#   contents: write
#   pages: write
#   id-token: write
#   issues: write
#   pull-requests: read  
  
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      issue_filenames: ${{ steps.get-issue-filenames.issue_filenames }}
      open_issues: ${{ steps.get-open-issues.open_issues }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Get Issue Filenames
      id: get-issue-filenames
      run: |
        ls issues/*.md > issue_filenames.tmp
        cat issue_filenames.tmp
        echo "[" > issue_filenames.json
        while read line; do
           echo \"$line\", >> issue_filenames.json
        done <issue_filenames.tmp
        echo "]" > issue_filenames.json
        issue_filenames=`cat issue_filenames.json`
        echo "issue_filenames=${issue_filenames}" 
        echo "issue_filenames=${issue_filenames}" >> "$GITHUB_OUTPUT"
    - name: Get Open Issues
      id: get-open-issues
      run: |
        gh issue list --state OPEN --json number,title,body,state >> open_issues.json
        cat open_issues.json
        open_issues=`cat open_issues.json`
        echo "open_issues=${open_issues}"
        echo "open_issues=${open_issues}" >> "$GITHUB_OUTPUT"
  
#     - name: Create Issue 1 From File
#       id: step1
#       uses: peter-evans/create-issue-from-file@v3
#       with:
#         title: Set up team deployments for prod and qa on Heroku, including Google OAuth setup
#         content-filepath: issues/issue00_set_up_deployment_on_heroku.md
#     - name: Add Issue 1 to Kanban board team03
#       uses: peter-evans/create-or-update-project-card@v1
#       with:
#         project-name: team03
#         column-name: Todo
#         issue-number: ${{ steps.step1.outputs.issue-number }}

