
name: 10-test
on:
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ github.token }}

permissions: write-all

#   contents: write
#   pages: write
#   id-token: write
#   issues: write
#   pull-requests: read  
  
jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      issue_filenames: ${{ steps.get-issue-filenames.issue_filenames }}
      open_issues: ${{ steps.get-open-issues.open_issues }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Create Label 
      run: |
        gh label create "auto" -f -d "This issue was created from a script" -c 909090

    - name: Get Issue Filenames
      id: get-issue-filenames
      run: |
        ls issues/*.md > issue_filenames.tmp
        cat issue_filenames.tmp
        echo "[" > issue_filenames.json
        while read line; do
           echo \"$line\", >> issue_filenames.json
        done <issue_filenames.tmp
        echo "]" >> issue_filenames.json
        # Next line removes all whitespace; see: https://www.baeldung.com/linux/remove-whitespace-from-file
        s=`tr -d "[:space:]" < issue_filenames.json`
        # Next line removes last trailing comma; see: https://unix.stackexchange.com/a/187920
        issue_filenames=`echo ${s%,*}${s##*,}`
        issue_filenames='["issues/issue01.md","issues/issue02.md"]'
        echo "issue_filenames=${issue_filenames}" 
        echo "issue_filenames=${issue_filenames}" >> "$GITHUB_OUTPUT"
        ls $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
    - name: Get Open Issues
      id: get-open-issues
      run: |
        gh issue list --state OPEN --json number,title,body,state >> open_issues.json
        cat open_issues.json
        open_issues=`cat open_issues.json`
        echo "open_issues=${open_issues}"
        echo "open_issues=${open_issues}" >> "$GITHUB_OUTPUT"
        ls $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

  create-issue:
    name: Create issue ${{ matrix.filename }}
    runs-on: ubuntu-latest
    needs: [initialize]

    strategy:
      matrix:
        filename: ${{ needs.outputs.issue_filenames }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Get title
      run: |
        title=`cat ${{ matrix.filename }} | head -n 1`
    - name: Create Issue From File
      id: step1
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: ${title}
        content-filepath: ${{ matrix.filename }}
        label: "auto"



#     - name: Create Issue 1 From File
#       id: step1
#       uses: peter-evans/create-issue-from-file@v3
#       with:
#         title: Set up team deployments for prod and qa on Heroku, including Google OAuth setup
#         content-filepath: issues/issue00_set_up_deployment_on_heroku.md
#     - name: Add Issue 1 to Kanban board team03
#       uses: peter-evans/create-or-update-project-card@v1
#       with:
#         project-name: team03
#         column-name: Todo
#         issue-number: ${{ steps.step1.outputs.issue-number }}

