
name: 20-create-project-board
on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: project board to create 
        options: 
        - team02
        - team03
        - team04
      org:
        type: choice
        description: organization in which to create project board
        options: 
        - ucsb-cs156-s23
        - ucsb-cs156-m23
        - ucsb-cs156-f23
        - ucsb-cs156
      team:
        type: choice
        description: team to create project board for
        options: 
        - s23-5pm-1
        - s23-5pm-2
        - s23-5pm-3
        - s23-5pm-4
        - s23-6pm-1
        - s23-6pm-2
        - s23-6pm-3
        - s23-6pm-4
        - s23-7pm-1
        - s23-7pm-2
        - s23-7pm-3
        - s23-7pm-4
      
  
env:
  GH_TOKEN: ${{ github.token }}

permissions: write-all
   # see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
  #  contents: read
  #  issues: write

jobs:
  set-things-up:
    runs-on: ubuntu-latest
    outputs:
      issue_filenames: ${{ steps.get-issue-filenames.outputs.issue_filenames }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Debugging output
      run: |
        echo "team=${{ github.event.inputs.team }}"
    - name: Get organization id
      run: |
        echo "org=${{ github.event.inputs.org }}"
        org_id=`gh api  -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/orgs/${{ github.event.inputs.org }} | jq .id `
        echo "org_id=${org_id}" >> "$GITHUB_ENV"
    - name: Create project
      run: |
        gh api graphql -f query='
          mutation{
            createProjectV2(
              input: {
                ownerId: ${{ env.org_id }},
                title: ${{ github.event.inputs.project}}-${{ github.event.inputs.team }}
              }
            ){
              projectV2 {
                id
              }
            }
          }'

        
        
        
    